### ISSUE TITLE
Error when drm4g resource edit is executed

### ISSUE THREAD

**Issue by cofinoa** [SantanderMetGroup/DRM4G#44]
```
$ drm4g resource edit
system() takes at most 1 argument (3 given)
```

**Comment by fernanqv** [comment]
This problem was solved in June (commit 9f2c3217c067e57b2c01908f89d8821eb8889f55) in the devel branch, but the fix has not been added to the drm4g pip package yet.

We will notify you as soon as we had added the fix to the package.
