### ISSUE TITLE
Change default value for clear subcommand 

### ISSUE THREAD

**Issue by cofinoa** [SantanderMetGroup/DRM4G#45]
```
drm4g clear
Stopping DRM4G .... 
  OK
Do you want to continue clearing DRM4G?  (Y/n) 
Clearing DRM4G .... 
  OK
```

**Comment by fernanqv** [comment]
We have modified the default value for clear subcommand to No. That's the new behaviour:

valva@pc7:~/DRM4G$ drm4g clear
Stopping DRM4G .... 
  OK
Do you want to continue clearing DRM4G?  (y/N) 
Starting DRM4G .... 
  OK
